# vsms — task runner.
#
# Expanding 16 models through `include_server_schema!` is memory-hungry enough
# to get rustc OOM-killed on a 32 GB machine at cargo's default job count. The
# recipes below cap concurrency rather than leaving each developer to discover
# that the hard way. See the `[profile.dev]` note in Cargo.toml.

# Cap build concurrency. Raise on a machine with headroom: `just jobs=8 check`.
jobs := "4"

_cargo := "CARGO_BUILD_JOBS=" + jobs + " cargo"

# `cratestack` binary used by client-gen/client-check (T3). Defaults to
# whatever `cratestack` resolves to on PATH; override for local dev with a
# pinned build, e.g. `just cratestack_bin=~/dev/cratestack/target/release/cratestack
# client-gen`. Requires >=0.7.8 — cratestack#456 fixed `Decimal` scalar TS
# emission (cratestack#455); anything older regenerates a client that fails
# to compile (`Cannot find name 'Decimal'`). CI installs the published
# 0.7.8 from crates.io onto PATH, so the default is correct there.
cratestack_bin := env_var_or_default("CRATESTACK_BIN", "cratestack")

# Show available recipes
help:
	@just --list

# Type-check the workspace
check:
	{{_cargo}} check --workspace --all-targets

# Run the test suite (unit + in-process — the 14 *_live_postgres.rs/*_live.rs
# suites stay #[ignore]d here; see `test-live`)
test:
	{{_cargo}} test --workspace

# Run every live-Postgres suite. `sms-test-support` starts (or reuses) one
# shared, self-healing Postgres 16 container and applies both migrations —
# needs Docker, nothing else. Safe to rerun: the container is named
# deterministically and reused, not recreated, across runs.
test-live:
	{{_cargo}} test --workspace -- --ignored

# Remove the shared test-harness container. Scoped by the exact label
# `sms-test-support` itself sets (`dev.vsms.test-harness=true`) — never by
# image or a bare name pattern, so this can never touch a container this
# workspace's tests did not create. Not required for correctness (the
# harness self-heals on its own next run) — this is just for a developer
# who wants their machine back to zero right now.
test-live-clean:
	docker rm -f $(docker ps -aq --filter "label=dev.vsms.test-harness=true") 2>/dev/null || true

# Format, then lint with warnings as errors
lint:
	cargo fmt --all --check
	{{_cargo}} clippy --workspace --all-targets -- -D warnings

# Apply formatting
fmt:
	cargo fmt --all

# Licence and advisory audit
deny:
	cargo deny check

# Everything CI runs, in CI's order
all-checks: lint test
	./ci/assert-no-raw-sqlx.sh
	python3 ci/assert-state-machine-parity.py

# R2: the state diagram and the transition table must agree
parity:
	python3 ci/assert-state-machine-parity.py

# Print the generated route table. Needs no database.
routes:
	{{_cargo}} run -p sms-gateway -- routes

# Apply migrations to a scratch database, run the state-machine assertions, drop it
schema-check:
	createdb vsms_check
	DATABASE_URL=postgres://localhost/vsms_check ./ci/apply-migrations.sh
	psql postgres://localhost/vsms_check -v ON_ERROR_STOP=1 -f ci/test-state-machine.sql
	dropdb vsms_check

# Regenerate 0002_bootstrap from §2.10 of the design doc
bootstrap-sql:
	python3 ci/gen-bootstrap-sql.py schema/migrations/postgres/0002_bootstrap/up.sql

# Regenerate packages/sms-client from schema/schema.cstack (T3). Per the
# owner's standing rule, generated code is never committed — this package
# is gitignored except `package.json` (see the .gitignore comment there
# and packages/sms-client/GENERATING.md) and must be regenerated after
# every `pnpm install`, before anything (`tsc`, `turbo`, `pnpm run build`)
# consumes it. `--base-path ''` is load-bearing — the server serves routes
# at `/`, not the generator's `/api` default. Also applies the DO-NOT-EDIT
# README banner (see ci/postprocess-sms-client-readme.mjs) as a
# deterministic, reproducible post-processing step, not a one-off hand-edit.
client-gen:
	{{cratestack_bin}} generate-typescript --schema schema/schema.cstack \
		--out packages/sms-client --package-name @vsms/sms-client --base-path ''
	node ci/postprocess-sms-client-readme.mjs packages/sms-client/README.md

# The drift gate over packages/sms-client that still means something once
# nothing is committed (T3). There used to be a second gate here —
# "does the committed client match schema/schema.cstack?" — but with no
# committed client there is nothing for it to diff against; it would
# assert nothing, so it was removed rather than kept as decoration.
#
# What remains, and matters more than that removed gate ever did: does
# every route the freshly generated client calls exist on the pinned
# server's real route table? The client can be generated by any
# `cratestack` CLI version, but `sms-gateway` is built from the pinned
# library family (=0.6.7), and AGENTS.md already documents these
# diverging for `migrate diff` on this machine. A CLI/library route-shape
# skew would 404 in production and nothing else here would catch it.
client-check: client-gen
	{{_cargo}} build -p sms-gateway
	node ci/assert-client-routes-match-server.mjs

# Bring up the full demo chain — scratch Postgres, sms-gateway, sms-worker
# (dispatch,scheduler,jobs), sms-fake-orange, and the admin console, wired
# together with a provisioned client — and leave it running in the
# background. NOT for production: sms-fake-orange impersonates Orange
# Cameroon's API and sends no real SMS. See scripts/demo.sh and
# docs/runbooks/getting-started.md §5-8 for what this automates.
demo:
	./scripts/demo.sh up

# Stop everything `just demo` started and remove its scratch Postgres
# container (by exact name only — never touches anything else).
demo-down:
	./scripts/demo.sh down

# What's currently running from `just demo`.
demo-status:
	./scripts/demo.sh status

# #160: the joined integration story — brings up `just demo`'s stack (via
# scripts/demo.sh, reused not reimplemented), provisions a SECOND client
# against the same App ("external integrator"), sends through
# examples/rust/sms-send authenticated as that integrator over real HTTP,
# then polls GET /messages/{id} AS THE CONSOLE's own credential — the
# same route packages/gateway/src/messages.ts's getMessageById calls —
# until that exact message id reaches `delivered`. Fails loudly (non-zero
# exit, a named step) if any link in the chain breaks. See
# docs/runbooks/e2e-integration.md for what this proves, what it fakes
# (Orange, via sms-fake-orange — #36's handset gate is unaffected), and
# why both clients share one App.
e2e-integration:
	./scripts/e2e-integration.sh
