//! `Command::RecordRouteValidation` (#64) — see that variant's own doc
//! comment in `main.rs` for why this writes through the plain generic
//! delegate under a stand-in `operator`-role context.

use anyhow::{Context, Result, bail};
use cratestack::sqlx::postgres::PgPoolOptions;
use sms_api::schema::Cratestack;
use sms_api::{Principal, PrincipalKind};

/// `Command::RecordRouteValidation`'s flags. See
/// `Command::RecordRouteValidation`'s own doc comment in `main.rs` — the
/// enum variant carries the "why", this struct only carries the flags
/// themselves.
#[derive(Debug, clap::Args)]
pub(crate) struct RecordRouteValidationArgs {
    #[arg(long, env = "DATABASE_URL")]
    pub(crate) database_url: String,

    /// The `Route.id` this validation covers.
    #[arg(long)]
    pub(crate) route_id: String,

    /// Which network's handset actually ran the check — `mtn`,
    /// `orange`, `camtel`, `nexttel`, or `unknown`.
    #[arg(long)]
    pub(crate) operator: String,

    /// The human who physically looked at the handset — free text, not
    /// necessarily the identity this command's own database
    /// credentials authenticate as. See `RouteValidation.performedBy`'s
    /// own `schema.cstack` comment.
    #[arg(long)]
    pub(crate) performed_by: String,

    /// What the sender ID should have displayed.
    #[arg(long)]
    pub(crate) expected_sender_id: String,

    /// What the recipient's handset actually displayed. §6.4's own
    /// named grey-route symptom: "sender ID silently replaced with a
    /// numeric string."
    #[arg(long)]
    pub(crate) observed_sender_id: String,

    /// Present if the handset displayed what was expected; absent if
    /// it didn't.
    #[arg(long)]
    pub(crate) passed: bool,

    #[arg(long)]
    pub(crate) notes: Option<String>,
}

/// `Command::RecordRouteValidation`'s own `--operator` flag, parsed by hand
/// rather than a `clap::ValueEnum` on `OperatorCode` — that type is
/// generated by `include_server_schema!` and this binary doesn't control
/// its derives. Matches `sms_api::schema::OperatorCode`'s five variants
/// verbatim.
fn parse_operator_code(value: &str) -> Result<sms_api::schema::OperatorCode> {
    use sms_api::schema::OperatorCode;
    match value {
        "mtn" => Ok(OperatorCode::mtn),
        "orange" => Ok(OperatorCode::orange),
        "camtel" => Ok(OperatorCode::camtel),
        "nexttel" => Ok(OperatorCode::nexttel),
        "unknown" => Ok(OperatorCode::unknown),
        other => bail!("--operator {other:?} is not one of mtn, orange, camtel, nexttel, unknown"),
    }
}

/// `Command::RecordRouteValidation`'s body (#64) — see that variant's own
/// doc comment for why this writes through the plain generic delegate
/// rather than a `Procedures` method, and why under a stand-in
/// `operator`-role context rather than `system`: `RouteValidation.create`'s
/// own `@@allow` already admits a human `operator`/`admin`/`owner`, the
/// same shape `ProvisionUser`'s own `owner`-context write above uses for
/// an equivalent bootstrap-tool case. Takes [`RecordRouteValidationArgs`]
/// directly rather than the whole `Command`: `main`'s own dispatch already
/// extracted it from `Command::RecordRouteValidation` at the match site.
pub(crate) async fn record_route_validation_command(args: RecordRouteValidationArgs) -> Result<()> {
    let RecordRouteValidationArgs {
        database_url,
        route_id,
        operator,
        performed_by,
        expected_sender_id,
        observed_sender_id,
        passed,
        notes,
    } = args;

    let operator = parse_operator_code(&operator)?;

    let pool = PgPoolOptions::new()
        .max_connections(4)
        .connect(&database_url)
        .await
        .context("connecting to Postgres")?;
    let db = Cratestack::builder(pool).build();
    let ctx = Principal {
        sub: "sms-gateway:record-route-validation:operator".to_owned(),
        kind: PrincipalKind::User,
        role: "operator".to_owned(),
        app_id: String::new(),
    }
    .into_context();

    let seeded = db
        .route_validation()
        .create(sms_api::schema::CreateRouteValidationInput {
            routeId: route_id.clone(),
            operator,
            performedBy: performed_by,
            expectedSenderId: expected_sender_id.clone(),
            observedSenderId: observed_sender_id.clone(),
            passed,
            notes,
        })
        .run(&ctx)
        .await
        .context("creating the RouteValidation row — check that --route-id names a real Route")?;

    let verdict = if passed { "PASSED" } else { "FAILED" };
    println!("recorded route validation: {verdict} (id={})", seeded.id);
    println!("  route:    {route_id}");
    println!("  operator: {operator:?}");
    println!("  expected sender id: {expected_sender_id}");
    println!("  observed sender id: {observed_sender_id}");
    if expected_sender_id != observed_sender_id {
        println!(
            "  WARNING: observed sender id does not match expected — this is §6.4's own named \
             grey-route symptom. See docs/runbooks/grey-route-validation.adoc for next steps."
        );
    }
    Ok(())
}
