-- 0004_import_to_imported / up.sql
--
-- cratestack 0.13 reserves `import` (multi-file schemas), so the enum variants
-- `OptOutSource.import` and `ConsentChannel.import` are `imported` in
-- schemas/vsms.cstack. 0001_init has already been applied to deployed
-- databases, so it is left byte-for-byte alone and this migration moves the
-- stored value instead.
--
-- Generated by `cratestack migrate diff` against a baseline snapshot of the
-- previous schema (the two DROP/ADD CONSTRAINT pairs), with the data
-- rewrite hand-added between each drop and add. It cannot live in
-- up.pre.sql: that runs before this file, while the old CHECK still refuses
-- 'imported'. Everything runs in the one transaction sms-migrate opens.

ALTER TABLE consent_records DROP CONSTRAINT consent_records_channel_enum_check;

ALTER TABLE opt_outs DROP CONSTRAINT opt_outs_source_enum_check;

UPDATE consent_records SET channel = 'imported' WHERE channel = 'import';

UPDATE opt_outs SET source = 'imported' WHERE source = 'import';

ALTER TABLE consent_records ADD CONSTRAINT consent_records_channel_enum_check CHECK (channel IN ('web_form', 'api', 'ivr', 'paper_form', 'verbal', 'sms_keyword', 'imported', 'admin'));

ALTER TABLE opt_outs ADD CONSTRAINT opt_outs_source_enum_check CHECK (source IN ('inbound_stop', 'admin', 'imported', 'operator'));
