//! The one-shot migration runner — §9.2's "which component applies
//! migrations, when, and what happens if two instances start at once."
//!
//! Replaces `deploy/migrate.Dockerfile`'s old `postgres:16-alpine` + `psql`
//! shell script (`deploy/migrate.sql`) with a small Rust binary that embeds
//! the same SQL at *compile* time via [`include_str!`] rather than `COPY`ing
//! `.sql` files into the image and shelling out to `psql` at *run* time.
//! `cratestack-sqlx` already vendors `sqlx-core`/`sqlx-postgres` under
//! `cratestack::sqlx` (`backends/crates/sms-api`'s own `main.rs` already uses
//! `cratestack::sqlx::postgres::PgPoolOptions`) — this binary is the first
//! to reach past that facade for [`cratestack::sqlx::raw_sql`], the one
//! piece deploy/migrate.sql's own logic actually needs and `CrateStack`'s
//! own generated delegates have no reason to expose.
//!
//! This is **not** an adoption of `sqlx`'s own migration framework (the
//! `sqlx::migrate!` macro, its `_sqlx_migrations` bookkeeping table, its
//! `<version>_<description>.sql` naming convention). That framework's own
//! directory scanner (`sqlx-core`'s `MigrationSource for &Path`, already
//! reachable through `cratestack::sqlx::migrate` with no new dependency)
//! only reads flat files directly inside one directory, named
//! `<VERSION>_<DESCRIPTION>.sql`, and silently skips anything that isn't a
//! file — confirmed by reading that resolver's own source, not assumed.
//! It cannot see this repo's `<name>/up.sql` layout at all, and that
//! layout isn't ours to change: `cratestack migrate diff --out-dir
//! backends/migrations/postgres --name <name>` is what produces it, and
//! `AGENTS.md`'s "never hand-edit" rule means the fix is not reshaping
//! generated output to fit a library's convention. Instead this ports
//! `deploy/migrate.sql`'s own `schema_migrations` bookkeeping logic
//! statement-for-statement into Rust: same advisory lock, same
//! per-migration "already applied?" check. The `.sql` this runs is
//! unchanged, byte-for-byte, from what `psql \i` used to run — only the
//! runner changed.
//!
//! # Discovery, not a hand-maintained list
//!
//! [`build.rs`](build.rs) walks `backends/migrations/postgres` at compile
//! time and generates the `MIGRATIONS` array below from whatever
//! subdirectories it finds an `up.sql` in, in lexical order — the same
//! directory `ci/apply-migrations.sh`'s own glob loop and
//! `backends/crates/sms-test-support`'s own `migration_dirs()` already read. A
//! fourth migration lands in `MIGRATIONS` the moment its directory exists;
//! nothing in this file needs editing. The library-bookkeeping DDL that
//! used to live at `ci/idempotency-table.sql` and be a hand-maintained
//! fourth entry has relocated to `backends/migrations/postgres/
//! 0003_idempotency_table/up.sql` for exactly this reason — see that
//! file's own header for why it belongs in this directory at all despite
//! not being `cratestack`-generated.
//!
//! # R1
//!
//! Raw `sqlx` calls, not a `CrateStack` delegate — `cargo xtask no-raw-sqlx`
//! allowlists this file by path. This is not a new exception: "migrations"
//! was already one of R1's four named exceptions
//! (`CONTRIBUTING.md`) before this binary existed; `deploy/migrate.sql`
//! was simply the exception's previous form.
//!
//! # Why a dedicated `PgConnection`, not a `Pool`
//!
//! `pg_advisory_lock` is session-scoped: the lock lives on whichever
//! Postgres backend process holds the connection, and is released the
//! moment that session ends. `backends/crates/sms-worker/src/lease.rs` already
//! documents the trap a `Pool`'s `PoolConnection` sets here — it returns to
//! the pool rather than closing on drop, so a lock taken on a pooled
//! connection can silently outlive the code that took it, on a session a
//! later, unrelated query then reuses. A one-shot process like this one
//! exits immediately after either success or a propagated `Err`, so a bare
//! `PgConnection` closing on drop is sufficient — Postgres releases the
//! advisory lock the instant that socket closes, no explicit unlock
//! required on the error path. The happy path still unlocks explicitly
//! (matching `deploy/migrate.sql`'s own final statement), simply because
//! it costs nothing and keeps the two paths symmetric to read.

use anyhow::{Context, Result};
use cratestack::sqlx::{Connection, PgConnection};
use tracing::info;

/// A single named migration to check for and, if missing, apply — mirrors
/// one `\if`/`\else` block of `deploy/migrate.sql` exactly.
struct Migration {
    name: &'static str,
    sql: &'static str,
}

/// Generated by [`build.rs`](build.rs) from every subdirectory of
/// `backends/migrations/postgres` that contains an `up.sql`, in lexical
/// (= apply) order, each embedded via `include_str!` at compile time —
/// see this module's own "Discovery, not a hand-maintained list" doc for
/// why. `include!` rather than a `mod` because the generated file is a
/// single expression (an array literal), not a set of items.
const MIGRATIONS: &[Migration] = include!(concat!(env!("OUT_DIR"), "/migrations.rs"));

/// Same key `deploy/migrate.sql` used (`hashtext('vsms_migrate')`) — stable
/// across runs, readable in `pg_locks` next to a role name, and confirmed
/// non-colliding with `backends/crates/sms-worker/src/lease.rs`'s own advisory-lock
/// namespace (that one uses the two-argument `(classid, objid)` form,
/// which Postgres hashes through an entirely different code path than the
/// single-bigint form used here).
const ADVISORY_LOCK_SQL: &str = "SELECT pg_advisory_lock(hashtext('vsms_migrate'))";
const ADVISORY_UNLOCK_SQL: &str = "SELECT pg_advisory_unlock(hashtext('vsms_migrate'))";

const ENSURE_BOOKKEEPING_TABLE_SQL: &str = "\
    CREATE TABLE IF NOT EXISTS public.schema_migrations (\n\
    \x20 name        text PRIMARY KEY,\n\
    \x20 applied_at  timestamptz NOT NULL DEFAULT now()\n\
    )";

#[tokio::main]
async fn main() -> Result<()> {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| "sms_migrate=info".into()),
        )
        .init();

    let database_url = std::env::var("DATABASE_URL").context("DATABASE_URL must be set")?;

    // A dedicated, unpooled connection — see this module's own doc for why.
    let mut conn = PgConnection::connect(&database_url)
        .await
        .context("connecting to Postgres")?;

    cratestack::sqlx::raw_sql(ADVISORY_LOCK_SQL)
        .execute(&mut conn)
        .await
        .context("acquiring the migration advisory lock")?;

    // Everything from here on runs under the lock. Any `?` below returns
    // early and drops `conn` without an explicit unlock — safe, per this
    // module's own doc, because a dropped `PgConnection` closes its
    // session immediately and Postgres releases the lock with it.
    run_migrations(&mut conn).await?;

    cratestack::sqlx::raw_sql(ADVISORY_UNLOCK_SQL)
        .execute(&mut conn)
        .await
        .context("releasing the migration advisory lock")?;

    info!("migrations up to date");
    Ok(())
}

/// Applies [`MIGRATIONS`] in order, skipping any already recorded in
/// `public.schema_migrations` — the exact behaviour of
/// `deploy/migrate.sql`'s own `\if :applied` guard per migration.
async fn run_migrations(conn: &mut PgConnection) -> Result<()> {
    cratestack::sqlx::raw_sql(ENSURE_BOOKKEEPING_TABLE_SQL)
        .execute(&mut *conn)
        .await
        .context("ensuring public.schema_migrations exists")?;

    for migration in MIGRATIONS {
        let already_applied: bool = cratestack::sqlx::query_scalar::<_, bool>(
            "SELECT EXISTS(SELECT 1 FROM public.schema_migrations WHERE name = $1)",
        )
        .bind(migration.name)
        .fetch_one(&mut *conn)
        .await
        .with_context(|| format!("checking whether {} was already applied", migration.name))?;

        if already_applied {
            info!(migration = migration.name, "already applied — skipping");
            continue;
        }

        info!(migration = migration.name, "applying");
        // Wrapped in an implicit transaction by `raw_sql` itself when the
        // text contains more than one statement (sqlx's own documented
        // behaviour) — stricter than the old `psql \i` path, which
        // auto-committed each statement individually unless the script
        // opened its own `BEGIN`. None of the committed migrations use
        // anything transaction-incompatible (no `CREATE INDEX
        // CONCURRENTLY` — checked directly, not assumed, and worth
        // rechecking if a future migration ever needs one), so this is a
        // strict improvement: a failure partway through a migration now
        // rolls back cleanly instead of leaving that migration half-applied.
        cratestack::sqlx::raw_sql(migration.sql)
            .execute(&mut *conn)
            .await
            .with_context(|| format!("applying migration {}", migration.name))?;

        cratestack::sqlx::query("INSERT INTO public.schema_migrations (name) VALUES ($1)")
            .bind(migration.name)
            .execute(&mut *conn)
            .await
            .with_context(|| format!("recording {} as applied", migration.name))?;
    }

    Ok(())
}
