#![doc = include_str!("main.md")]

use anyhow::{Context, Result};
use cratestack::sqlx::{Connection, PgConnection};
use tracing::info;

/// A single named migration to check for and, if missing, apply — mirrors
/// one `\if`/`\else` block of `deploy/migrate.sql` exactly, plus the
/// optional `up.pre.sql` cratestack migrate diff scaffolds for a blocking
/// migration (see this module's own "up.pre.sql" doc section).
struct Migration {
    name: &'static str,
    pre_sql: Option<&'static str>,
    sql: &'static str,
}

/// Generated by [`build.rs`](build.rs) from every subdirectory of
/// `backends/migrations/postgres` that contains an `up.sql`, in lexical
/// (= apply) order, each embedded via `include_str!` at compile time —
/// see this module's own "Discovery, not a hand-maintained list" doc for
/// why. `include!` rather than a `mod` because the generated file is a
/// single expression (an array literal), not a set of items.
const MIGRATIONS: &[Migration] = include!(concat!(env!("OUT_DIR"), "/migrations.rs"));

/// Same key `deploy/migrate.sql` used (`hashtext('vsms_migrate')`) — stable
/// across runs, readable in `pg_locks` next to a role name, and confirmed
/// non-colliding with `backends/crates/sms-worker/src/lease.rs`'s own advisory-lock
/// namespace (that one uses the two-argument `(classid, objid)` form,
/// which Postgres hashes through an entirely different code path than the
/// single-bigint form used here).
const ADVISORY_LOCK_SQL: &str = "SELECT pg_advisory_lock(hashtext('vsms_migrate'))";
const ADVISORY_UNLOCK_SQL: &str = "SELECT pg_advisory_unlock(hashtext('vsms_migrate'))";

const ENSURE_BOOKKEEPING_TABLE_SQL: &str = "\
    CREATE TABLE IF NOT EXISTS public.schema_migrations (\n\
    \x20 name        text PRIMARY KEY,\n\
    \x20 applied_at  timestamptz NOT NULL DEFAULT now()\n\
    )";

#[tokio::main]
async fn main() -> Result<()> {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| "sms_migrate=info".into()),
        )
        .init();

    let database_url = std::env::var("DATABASE_URL").context("DATABASE_URL must be set")?;

    // A dedicated, unpooled connection — see this module's own doc for why.
    let mut conn = PgConnection::connect(&database_url)
        .await
        .context("connecting to Postgres")?;

    cratestack::sqlx::raw_sql(ADVISORY_LOCK_SQL)
        .execute(&mut conn)
        .await
        .context("acquiring the migration advisory lock")?;

    // Everything from here on runs under the lock. Any `?` below returns
    // early and drops `conn` without an explicit unlock — safe, per this
    // module's own doc, because a dropped `PgConnection` closes its
    // session immediately and Postgres releases the lock with it.
    run_migrations(&mut conn).await?;

    cratestack::sqlx::raw_sql(ADVISORY_UNLOCK_SQL)
        .execute(&mut conn)
        .await
        .context("releasing the migration advisory lock")?;

    info!("migrations up to date");
    Ok(())
}

/// Applies [`MIGRATIONS`] in order, skipping any already recorded in
/// `public.schema_migrations` — the exact behaviour of
/// `deploy/migrate.sql`'s own `\if :applied` guard per migration.
async fn run_migrations(conn: &mut PgConnection) -> Result<()> {
    cratestack::sqlx::raw_sql(ENSURE_BOOKKEEPING_TABLE_SQL)
        .execute(&mut *conn)
        .await
        .context("ensuring public.schema_migrations exists")?;

    for migration in MIGRATIONS {
        let already_applied: bool = cratestack::sqlx::query_scalar::<_, bool>(
            "SELECT EXISTS(SELECT 1 FROM public.schema_migrations WHERE name = $1)",
        )
        .bind(migration.name)
        .fetch_one(&mut *conn)
        .await
        .with_context(|| format!("checking whether {} was already applied", migration.name))?;

        if already_applied {
            info!(migration = migration.name, "already applied — skipping");
            continue;
        }

        info!(migration = migration.name, "applying");
        // A real, explicit transaction — see this module's own
        // "up.pre.sql" doc for why: cratestack's own generator promises
        // up.pre.sql "runs immediately before up.sql, inside the SAME
        // transaction... both halves land or neither does"
        // (cratestack-migrate-0.11.0/src/emit/postgres/up_pre.rs). Two
        // separate `raw_sql` calls against a bare connection would each
        // open and close their own implicit transaction (sqlx's own
        // documented behaviour for a multi-statement string), which
        // satisfies that guarantee only by accident today — every
        // committed `up.pre.sql` is comment-only — and would silently
        // stop satisfying it the moment a real one exists. Folding the
        // bookkeeping `INSERT` into the same transaction too is a step
        // further than upstream's own guarantee (which only covers the
        // two SQL files): free to do here, and it means a crash right
        // after a migration applies can never leave it un-recorded.
        // None of the committed migrations use anything
        // transaction-incompatible (no `CREATE INDEX CONCURRENTLY` —
        // checked directly, not assumed, and worth rechecking if a
        // future migration ever needs one).
        let mut tx = conn
            .begin()
            .await
            .with_context(|| format!("opening a transaction for {}", migration.name))?;

        if let Some(pre_sql) = migration.pre_sql {
            cratestack::sqlx::raw_sql(pre_sql)
                .execute(&mut *tx)
                .await
                .with_context(|| format!("applying {}/up.pre.sql", migration.name))?;
        }

        cratestack::sqlx::raw_sql(migration.sql)
            .execute(&mut *tx)
            .await
            .with_context(|| format!("applying migration {}", migration.name))?;

        cratestack::sqlx::query("INSERT INTO public.schema_migrations (name) VALUES ($1)")
            .bind(migration.name)
            .execute(&mut *tx)
            .await
            .with_context(|| format!("recording {} as applied", migration.name))?;

        tx.commit()
            .await
            .with_context(|| format!("committing {}", migration.name))?;
    }

    Ok(())
}
